### ISSUE TITLE
\*as\*cendant syntax

### ISSUE THREAD

**Issue by Liebranca** [Liebranca/kvr#5]
Figure 0:

```$
var@0 =/#/op= var@1;
```

`mamm` will have trouble with this because it's fetch first token, check if it's a fetch, then oppy-poppin and finally solving -- and all to repeat the process once again; except this time generate actual instruction tokens and check whether the first oppy is an equals, kush or e-oppy.

This doesn't make any sense. Put instruction then eval once, simple. You know the minimum number of args firsthand, and \*all\* tokens are translated in the same run.

Thus, figure 1:
```$
cpy var@0, var@1
```

I have inadvertently developed an interpreter which has a preference for this kind of mock-assembly syntax. And I like it a lot.

So: time to ascend beyond re-thinking and re-designs, this is what we're doing now.

#

### TODOs

- [x] `cpy` a, b -> a = b;
- [x] `mov` a, b -> a = b; b ^= b;
- [x] `wap` a, b -> c = a; a = b; b = c;
- [x] `wed` type -> sets typing mode; implicit casting

#

- [x] `jif` a, b -> jump to a if b
- [x] `eif` a, b -> jump to b if not a
- [x] `entry` s -> defines s as program entry point
- [x] `exit` x -> stops program and returns x

#

- [x] `add` a, b -> a += b;
- [x] `sub` a, b -> a -= b;
- [x] `mul` a, b -> a \*= b;
- [x] `div` a, b -> a /= b;
- [x] `mod` a, b -> a %= b;

#

- [x] `and` a, b -> a &= b;
- [x] `or` a, b -> a |= b;
- [x] `xor` a, b -> a ^= b;
- [x] `nand` a, b -> a = !(a&b);
- [x] `nor` a, b -> a = !(a|b);
- [x] `xnor` a, b -> a = ~(a^b);
- [x] `shl` a, b -> a<<b; cpy a, a << b;
- [x] `shr` a, b -> a>>b; cpy a, a >> b;

#

- [x] `til` a -> a = ~a
- [x] `cl` a -> a^=a
- [x] `clm` a, b -> a&=~b
- [x] `not` a -> cflg set/unset non-zero a; a=!a; returns a==0;

#

- [x] `lis` a, b -> define/redefine a as an alias for b
- [x] `buf` a -> set buffer idex to a
- [x] `sow` varargs -> write varargs to current buffer
- [x] `reap` a -> execute op idex a for current buffer

**Comment by Liebranca** [comment]
A lot has changed about Peso in the last few months; most of the workload is now done over at `avtomat` and in a more refined fashion. As for `ESPECTRO`, it is now `shb7` and not currently under development, though I do have plans for the near future.

For now, I am closing this issue and the associated project just to make sure we don't leave things just 'hanging', m'kay?
